/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import CambioColor.BMPyJPEG;
import CambioColor.BlancoNegro;
import CambioColor.CopiaJPEG;
import CambioColor.FiltrosColores;
import CambioColor.Rotar;
import Handlers.JPEGHandler;
import ListasEnlazadas.ImagenP;
import ListasEnlazadas.ListaImagen;
import ListasEnlazadas.ListaUsuario;
import ListasEnlazadas.Usuario;
import javax.swing.DefaultListModel;

/**
 *
 * @author rodri
 */
public class Convertidor extends javax.swing.JFrame {
private ListaUsuario nuevaListas;
private Usuario usuarioRe;
private ImagenP imagen;
private String foto;
private String nombreFoto;
String Ruta;
    /**
     * Creates new form Convertidor
     */
    public Convertidor() {
        initComponents();
    }

    private void actualizarCategorias(){
        
        this.jComboBox2.removeAllItems();
         if(this.jComboBox1.getSelectedItem() != null){
        this.usuarioRe = (Usuario)nuevaListas.find(String.valueOf(this.jComboBox1.getSelectedItem()));
        String [] Categorias = (String[]) usuarioRe.getGaleria().get(0);
        System.out.println(Categorias.length);
       
        for (int i = 0; i < Categorias.length; i++) {
        jComboBox2.addItem(Categorias[i]);
        }}}
    
    
    private void ActualizarCB(){
        this.jComboBox1.removeAllItems();
        String [] Usuarios = (String[]) nuevaListas.get(0);
        System.out.println(Usuarios.length);
       
        for (int i = 0; i < Usuarios.length; i++) {
        jComboBox1.addItem(Usuarios[i]);  
        
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        OPCION = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        CB1 = new javax.swing.JRadioButton();
        CB2 = new javax.swing.JRadioButton();
        CB4 = new javax.swing.JRadioButton();
        CB3 = new javax.swing.JRadioButton();
        CB5 = new javax.swing.JRadioButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(255, 0, 153));
        jLabel1.setText("Usuario");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 17, 48, -1));

        jComboBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox1MouseClicked(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 13, 107, -1));

        jLabel2.setForeground(new java.awt.Color(255, 0, 153));
        jLabel2.setText("Categoria");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(281, 17, 62, -1));

        getContentPane().add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 13, 93, -1));

        jButton1.setBackground(new java.awt.Color(153, 0, 204));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Agregar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(505, 13, -1, -1));

        CB1.setBackground(new java.awt.Color(0, 0, 0));
        OPCION.add(CB1);
        CB1.setForeground(new java.awt.Color(255, 0, 153));
        CB1.setText("JPEG a BMP y viceversa");
        getContentPane().add(CB1, new org.netbeans.lib.awtextra.AbsoluteConstraints(281, 96, -1, -1));

        CB2.setBackground(new java.awt.Color(0, 0, 0));
        OPCION.add(CB2);
        CB2.setForeground(new java.awt.Color(255, 0, 153));
        CB2.setText("Copia JPEG");
        getContentPane().add(CB2, new org.netbeans.lib.awtextra.AbsoluteConstraints(281, 139, -1, -1));

        CB4.setBackground(new java.awt.Color(0, 0, 0));
        OPCION.add(CB4);
        CB4.setForeground(new java.awt.Color(255, 0, 153));
        CB4.setSelected(true);
        CB4.setText("Modificar Imgaen");
        getContentPane().add(CB4, new org.netbeans.lib.awtextra.AbsoluteConstraints(281, 225, -1, -1));

        CB3.setBackground(new java.awt.Color(0, 0, 0));
        OPCION.add(CB3);
        CB3.setForeground(new java.awt.Color(255, 0, 153));
        CB3.setText("Rojo, Verde, Azul, Sepia");
        getContentPane().add(CB3, new org.netbeans.lib.awtextra.AbsoluteConstraints(281, 182, -1, -1));

        CB5.setBackground(new java.awt.Color(0, 0, 0));
        OPCION.add(CB5);
        CB5.setForeground(new java.awt.Color(255, 0, 153));
        CB5.setText("Blanco y Negro");
        getContentPane().add(CB5, new org.netbeans.lib.awtextra.AbsoluteConstraints(281, 268, -1, -1));

        jButton2.setBackground(new java.awt.Color(153, 0, 204));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Ejecutar en Paralelo");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(556, 87, 157, 58));

        jButton3.setBackground(new java.awt.Color(153, 0, 204));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Salir");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(656, 13, -1, -1));

        jList1.setBackground(new java.awt.Color(153, 0, 204));
        jList1.setForeground(new java.awt.Color(255, 255, 255));
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "A que se veran las imagenes", "agregadas, segun la categoria ", "seleccionada del usuario" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 56, 170, 341));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6, 0, 750, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Menu nuevo = new Menu();
        nuevo.setListas(nuevaListas);
        nuevo.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jComboBox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MouseClicked
        // TODO add your handling code here:
        actualizarCategorias();
    }//GEN-LAST:event_jComboBox1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        ActualizarLista();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        ListaImagen img = (ListaImagen) usuarioRe.getGaleria().find(String.valueOf(jComboBox2.getSelectedItem()));
        ImagenP picture = img.start;
        
        for (int i = 0; i < img.getSize(); i++) {
            foto = picture.getPath_();
        nombreFoto = picture.getName();
       
        
        if(CB3.isSelected()){
              FiltrosColores rojo = new FiltrosColores(foto, nombreFoto, true, false, false, false, "Red-");
           FiltrosColores verde = new FiltrosColores(foto, nombreFoto, false, true, false, false, "Green-");
            FiltrosColores azul = new FiltrosColores(foto, nombreFoto, false, false, true, false, "Blue-");
            FiltrosColores sepia = new FiltrosColores(foto, nombreFoto, false,false, false, true, "Sepia-");
            try {
                System.out.println("COlores");
            JPEGHandler.runHandler(rojo);
            
            
            
        } catch (Exception e) {
            
        }
            try {
                JPEGHandler.runHandler(verde);
            } catch (Exception e) {
            }
            
            try {
                JPEGHandler.runHandler(azul);
            } catch (Exception e) {
            }
            try {
                JPEGHandler.runHandler(sepia);
            } catch (Exception e) {
            }
            
             picture = picture.getNext();
        }
        
         if(CB2.isSelected()){
             
            CopiaJPEG copy = new CopiaJPEG(foto, nombreFoto);
           copy.setCopiaBmp(true);
            
            try {
                System.out.println("JPEGtoBMP");
            JPEGHandler.runHandler(copy);
        } catch (Exception e) {
            
        }
             picture = picture.getNext();
        }
        
        if(CB1.isSelected()){
            BMPyJPEG bmp = new BMPyJPEG(foto, nombreFoto);
           
           
            try {
                System.out.println("JPEGtoBMP");
            JPEGHandler.runHandler(bmp);
        } catch (Exception e) {
        }
             picture = picture.getNext();
        }
        if(CB5.isSelected()){
        BlancoNegro bn = new BlancoNegro(foto, nombreFoto);
        try {
            System.out.println("JPEGtoBN");
            JPEGHandler.runHandler(bn);
        } catch (Exception e) {
        }
         picture = picture.getNext();
        }
        if (CB4.isSelected()){
        Rotar rot = new Rotar(foto,nombreFoto);
        try {
            System.out.println("JPEGtoConv");
            JPEGHandler.runHandler(rot);
        } catch (Exception e) {
        }
        }
        
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    public void setUsuarios(String usuario){
        this.usuarioRe = (Usuario)nuevaListas.find(usuario);
        ActualizarCB();
    }
    
    private void BuscarImagen(){
        
        ListaImagen img = (ListaImagen) usuarioRe.getGaleria().find(String.valueOf(jList1.getSelectedValue()));
       String [] Folder = (String[]) img.get(0);
        System.out.println(Folder.length);
       
        for (int i = 0; i < Folder.length; i++) {
        Ruta = String.valueOf(Folder[i]);  
        
        }
        
    }
    
    
    private void RutasImg(){
    ListaImagen img = (ListaImagen) usuarioRe.getGaleria().find(String.valueOf(jComboBox2.getSelectedItem()));
    String [] Folder = (String[])img.getRuta();
    }
    
    
    private void ActualizarLista(){
        ListaImagen img = (ListaImagen) usuarioRe.getGaleria().find(String.valueOf(jComboBox2.getSelectedItem()));
        DefaultListModel<String> listaC = new DefaultListModel<>();
        String [] Folder = (String[]) img.get(0);
        System.out.println(Folder.length);
       
        for (int i = 0; i < Folder.length; i++) {
        listaC.addElement(Folder[i]);   
        
        }
        jList1.setModel(listaC);
    }
    
    
    public void setListas(ListaUsuario nuevaListas){
        this.nuevaListas = nuevaListas;
        ActualizarCB();
        actualizarCategorias();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Convertidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Convertidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Convertidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Convertidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Convertidor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton CB1;
    private javax.swing.JRadioButton CB2;
    private javax.swing.JRadioButton CB3;
    private javax.swing.JRadioButton CB4;
    private javax.swing.JRadioButton CB5;
    private javax.swing.ButtonGroup OPCION;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
